# Generated by Django 4.2.7 on 2025-03-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='is_correct',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='user_ip',
            field=models.CharField(db_index=True, max_length=45),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['user_ip', 'is_correct'], name='questions_q_user_ip_d133be_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['-attempted_at'], name='questions_q_attempt_7816f8_idx'),
        ),
    ]
