# Generated by Django 5.1.6 on 2025-03-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_answer',
            field=models.CharField(max_length=255),
        ),
    ]
